#!/bin/bash

# A script for cleaning the directory from files or directories other than ones with the format yyyy-mm-ddThh-mm-ss
# Usage
#	-s / --source - path the the catalog

while getopts "s-:" opt
do
	case $opt in
		s) DIRPATH=$OPTARG ;;
		?) if [[ $1 = "--source" ]]
			then
		        	DIRPATH=$2
			else	
				echo Invalid option
				exit 1
			fi;;
	esac
done

if [ -z $DIRPATH ]
then
	DIRPATH=$PWD
fi

cd $DIRPATH

echo "---Usuniete pliki" > ../usuniete
echo "---Pozostawione pliki" > ../pozostawione

for i in $(ls)
do
	if [[ $i =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-2][0-9]-[0-5][0-9]-[0-9]{2}$ ]] && [ -d $i ]
	then
		echo $i >> ../pozostawione
	else
		echo $i >> ../usuniete
	        echo "rm -r $i"
	fi
done

cat ../pozostawione

echo ""

cat ../usuniete
