#!/bin/bash

# A script for cleaning the directory from files or directories other than ones with the format yyyy-mm-ddThh-mm-ss
# Usage
#	-s / --source - path the the catalog

while getopts "s:" opt
do
	case $opt in
		s) DIRPATH=$OPTARG ;;
		?) echo Invalid option
			exit 1;;
	esac
done

if [ -z $DIRPATH ]
then
	DIRPATH=$PWD
fi

cd $DIRPATH

echo "---Usuniete pliki" > ../usuniete
echo "---Pozostawione pliki" > ../pozostawione

for i in $(ls)
do
	if [ -f $i ]
	then
		echo $i >> ../usuniete
		rm $i
	fi

	if [ -d $i ]
	then
		if [[ $i=~[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-2][0-9]-[0-5][0-9]-[0-9]\{2\} ]]
		then
			echo $i >> ../pozostawione
		else
			echo $i >> ../usuniete
			rm -r $i
		fi
	fi
done

for i in $(cat ../pozostawione)
do
	echo $i
done

echo ""

for i in $(cat ../usuniete)
do
	echo $i
done

exit 0
